// facts.js

export const dailyFacts = [
  "💡 Did you know that sharks existed millions of years before trees ever grew on Earth?",
  "🌍 Did you know that Africa is the only continent situated in all four hemispheres?",
  "🧠 Fun Fact: Your brain uses 20% of your body’s total energy despite being only 2% of its weight!",
  "📱 Did you know the first mobile phone weighed over 1 kilogram and cost nearly $4,000?",
  "👩‍💻 Ada Lovelace, a woman in the 1800s, wrote the first computer algorithm — way before computers existed!",
  "🎓 Did you know? Studying in short bursts (like 25 minutes) boosts retention — it’s called the Pomodoro Technique!",
  "📖 Fact: Reading for 6 minutes can reduce stress levels by 68%.",
  "🇪🇬 Did you know the ancient Egyptians invented toothpaste using mint and salt?",
  "🚀 NASA’s Voyager 1, launched in 1977, is still traveling through space — and sending signals back!",
  "🕊️ Nelson Mandela forgave his jailers after 27 years in prison — a lesson in leadership and peace.",
  "🌌 Did you know that space is completely silent because there is no atmosphere to carry sound?",
  "🌋 The hottest place on Earth is Africa’s Sahara Desert, which can reach up to 136°F (58°C)!",
  "📏 Did you know that the Eiffel Tower can grow up to 6 inches in summer due to thermal expansion?",
  "🔬 Fun Fact: A single teaspoon of honey represents the lifetime work of 12 bees!",
  "💾 The first computer virus was created in 1971 and was called the Creeper virus.",
  "🎶 Many famous composers, like Beethoven, continued composing music even after losing their hearing.",
  "🍉 Did you know that watermelon is 92% water and makes a perfect hydrating snack?",
  "⚡ Lightning strikes the Earth about 100 times every second.",
  "🐢 The fastest land animal is the cheetah, capable of speeds up to 75 mph, but the fastest sea creature is the sailfish, at 68 mph.",
  "🏛️ Did you know the Library of Alexandria in Egypt was one of the largest libraries of the ancient world?",
  "🦠 A single human body has more bacterial cells than human cells — by a ratio of about 3:1!",
  "🎂 The world’s oldest known recipe is for beer and comes from ancient Mesopotamia (around 1800 BCE).",
  "🌱 Bamboo can grow up to 36 inches in 24 hours — that’s 1.5 inches per hour!",
  "🦒 A giraffe’s neck has the same number of vertebrae as a human’s — just seven, but each is 10 inches long!",
  "📚 The average person will spend about six months of their life waiting for red lights to turn green.",
  "🦋 Monarch butterflies migrate up to 3,000 miles from North America to central Mexico every year.",
  "🌞 The Sun is made of 73% hydrogen and 25% helium by mass.",
  "🔭 Did you know that a day on Venus is longer than a year on Venus? (It rotates once in 243 Earth days and orbits the Sun in 225 Earth days.)",
  "⚖️ A cubic inch of neutron star would weigh about 10 billion tons on Earth.",
  "🌌 The closest galaxy to us, Andromeda, is 2.5 million light‐years away but will collide with the Milky Way in about 4 billion years.",
  "🍫 Chocolate was once used as currency by the Aztecs and Mayans.",
  "📅 The Gregorian calendar lost about 10 days when it was first introduced in 1582 to correct spring equinox drift.",
  "🧊 Did you know that Antarctica is the only continent without reptiles or snakes?",
  "🕰️ Time dilation: Astronauts aboard the International Space Station age slightly slower than people on Earth due to Einstein’s theory of relativity.",
  "🪐 Jupiter’s Great Red Spot is a storm that’s been raging for over 350 years and is wider than Earth.",
  "🦉 Owls have asymmetrical ears, allowing them to pinpoint the location of faint sounds with incredible accuracy.",
  "🌊 The Mariana Trench is the deepest part of the ocean, reaching around 36,000 feet below sea level.",
  "🐌 Did you know that some snails can sleep up to 3 years during hibernation or aestivation?",
  "🤖 The term “robot” was first introduced in a 1920 play by Karel Čapek — ‘R.U.R.’ (Rossum’s Universal Robots).",
  "🔭 Edwin Hubble discovered that the universe is expanding in 1929, fundamentally changing our understanding of the cosmos.",
  "🦘 Kangaroos can’t walk backward, which is why they’re on Australia’s coat of arms symbolizing forward progress.",
  "🌏 Earth isn’t a perfect sphere; it’s an oblate spheroid—slightly flattened at the poles and bulging at the equator.",
  "🌿 Did you know bamboo can be harvested and regrown in 3–5 years? It’s one of the fastest‐growing plants in the world!",
  "🐝 Bees communicate by doing a “waggle dance” to show other bees where flowers are located.",
  "🪂 Skydiving records: The highest skydive was made by Felix Baumgartner from 128,000 feet in 2012!",
  "🌈 A single raindrop contains millions of water molecules, each moving randomly—no two raindrops are exactly alike.",
  "💡 Thomas Edison tested over 6,000 different materials for his lightbulb filament before he settled on carbonized bamboo.",
  "🔆 Did you know that Venus is the hottest planet, even though Mercury is closer to the Sun? Its thick atmosphere traps heat.",
  "👨‍🔬 Marie Curie is the only person to win Nobel Prizes in two different sciences (Physics in 1903, Chemistry in 1911).",
  "🌿 A single teaspoon of soil contains more microorganisms than there are people on Earth.",
  "🛰️ The first artificial satellite, Sputnik 1, was launched by the Soviet Union in 1957 and orbited at 18,000 mph.",
  "🧬 DNA: If you unraveled all the DNA in your body and stretched it end to end, it would reach to the Sun and back more than 600 times.",
  "🌞 Each second, the Sun emits enough energy to power human civilization for 500,000 years — yet we use only a tiny fraction.",
  "📚 Did you know the earliest known written story is the Epic of Gilgamesh, dating back to around 2100 BCE?",
  "🐘 Elephants are the only mammals that can’t jump, but they walk quietly and have incredible memory.",
  "🍄 Fungi are more closely related to animals than to plants in the tree of life.",
  "🌐 The internet weighs about the same as a strawberry—if you convert each electron that carries data into mass (E = mc²).",
  "🤝 Did you know people with higher levels of empathy have stronger neural connections in the brain’s social network?",
  "🧩 Puzzles strengthen the brain’s problem-solving networks and can even delay onset of dementia in older adults.",
  "🚞 The Trans‐Siberian Railway is the longest railway line in the world—over 9,289 kilometers (5,772 miles).",
  "👩‍🎨 Leonardo da Vinci wrote his notes backward (mirror writing) so that others couldn’t easily read his ideas.",
  "🌋 Mount Everest still grows about 4 mm each year due to tectonic activity.",
  "⚽ Did you know soccer (football) is the most watched sport globally, with over 4 billion fans around the world?",
  "📓 The world’s largest library is the Library of Congress in Washington, D.C., holding over 170 million items.",
  "🎨 Vincent van Gogh created over 2,100 artworks in just a 10-year career—many in his final years.",
  "🚌 The first city to have a public transit system was Paris, with horse-drawn omnibuses introduced in 1662.",
  "🐨 Koalas sleep up to 18-22 hours a day to conserve energy because eucalyptus leaves are low in nutrition.",
  "⚡ Lightning can heat the air around it to temperatures five times hotter than the surface of the Sun.",
  "📷 Did you know the first photograph ever taken took 8 hours of exposure time?",
  "🥇 A gold nugget large enough to fill the size of a US quarter is worth about $100 in scrap gold today, but centuries ago was priceless.",
  "🚂 The Orient Express originally ran from Paris to Istanbul—a luxurious 2,735-mile journey.",
  "🌠 Did you know many people worldwide have a meteorite in their backyard—over 60 000 meteorites have been found on Earth?",
  "🎓 In Finland, homework is very minimal, and students learn effectively through in-class interactive lessons.",
  "🦇 Bats are the only mammals capable of sustained flight and use echolocation to ‘see’ in complete darkness.",
  "⚖️ Did you know the heaviest naturally occurring element is uranium? It’s so dense that if you had a cube of pure uranium the size of a dice, it would weigh about 45 pounds.",
  "📏 The world’s tallest building is the Burj Khalifa in Dubai, at 2,722 feet (828 m).",
  "☕ Did you know coffee was discovered in Ethiopia by goats that “danced” after eating coffee cherries?",
  "📼 The first commercial home video game console was the Magnavox Odyssey, released in 1972.",
  "🏞️ The Amazon River carries more water than the next seven largest rivers combined.",
  "🌳 A mature oak tree can draw up to 50 gallons (190 L) of water out of the ground each day.",
  "💧 Did you know that water expands by 9% when it freezes, which is why ice floats on liquid water?",
  "🔭 The James Webb Space Telescope’s primary mirror is 6.5 meters wide—almost the size of a tennis court.",
  "🦕 Did you know that some dinosaurs were smaller than chickens—like the Microraptor, which was about the size of a crow?",
  "🥼 Linus Pauling is one of only two people to win two unshared Nobel Prizes (Chemistry in 1954, Peace in 1962).",
  "🔬 CRISPR gene editing can potentially cure genetic diseases—scientists just need to unlock safe delivery methods.",
  "🎧 Did you know headphones were originally invented in 1910 by Nathaniel Baldwin—he made them in his kitchen!",
  "🌈 A double rainbow occurs when sunlight reflects twice inside a raindrop, producing two arcs.",
  "🚢 The Titanic’s captain, Edward John Smith, was supposed to retire after that voyage—history took a tragic turn.",
  "☁️ Did you know that clouds can weigh more than a million pounds? A single cumulus cloud can weigh nearly 1.1 million pounds!",
  "🌱 The largest living organism on Earth is a fungus in Oregon, covering 2,385 acres (3.7 square miles).",
  "🏛️ The Parthenon in Greece is so precisely constructed that its columns are slightly convex to look straight from a distance.",
  "🐲 Komodo dragons have venomous bites—they produce toxins that prevent blood clotting in their prey."
];
